"""empty message

Revision ID: 34aa167b57b0
Revises: 48a942ae368e
Create Date: 2026-03-04 12:36:40.595192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34aa167b57b0'
down_revision = '48a942ae368e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_outer_id_key', 'employees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employees_outer_id_key', 'employees', ['outer_id'])
    # ### end Alembic commands ###
