"""empty message

Revision ID: 37d952496e53
Revises: d1f88c288329
Create Date: 2022-09-26 13:51:09.906769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d952496e53'
down_revision = 'd1f88c288329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dropbox_share_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'dropbox_share_url')
    # ### end Alembic commands ###
