"""empty message

Revision ID: 3996edc31fc9
Revises: 146cee77495a
Create Date: 2023-10-17 14:45:45.302933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3996edc31fc9'
down_revision = '146cee77495a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_big_product', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_big_product')
    # ### end Alembic commands ###
