"""empty message

Revision ID: 48a942ae368e
Revises: d8b2c1c1197f
Create Date: 2026-03-04 12:21:09.583821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a942ae368e'
down_revision = 'd8b2c1c1197f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('outer_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['outer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'outer_id')
    # ### end Alembic commands ###
