"""empty message

Revision ID: 81d58ac4ba3c
Revises: f575a4916a00
Create Date: 2023-03-07 09:25:19.973130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d58ac4ba3c'
down_revision = 'f575a4916a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('callbacks')
    # ### end Alembic commands ###
