"""empty message

Revision ID: a72a3b453113
Revises: 34aa167b57b0
Create Date: 2026-05-14 13:37:22.879944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72a3b453113'
down_revision = '34aa167b57b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_adobe_auto', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_adobe_auto')
    # ### end Alembic commands ###
