"""empty message

Revision ID: b30561c9a624
Revises: 37d952496e53
Create Date: 2022-09-26 16:38:14.720714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30561c9a624'
down_revision = '37d952496e53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
