"""empty message

Revision ID: b5ae3070b97d
Revises: a72a3b453113
Create Date: 2026-05-14 13:40:50.412801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ae3070b97d'
down_revision = 'a72a3b453113'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
