"""empty message

Revision ID: bf08662b8220
Revises: e31e49c08664
Create Date: 2022-12-15 12:43:39.580614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf08662b8220'
down_revision = 'e31e49c08664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('end_production_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'end_production_date')
    # ### end Alembic commands ###
