"""empty message

Revision ID: d1f88c288329
Revises: 85d347cecb06
Create Date: 2022-09-19 14:44:41.569201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f88c288329'
down_revision = '85d347cecb06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'parent_id')
    # ### end Alembic commands ###
