"""empty message

Revision ID: e31e49c08664
Revises: 92ce568c9fe6
Create Date: 2022-12-13 12:17:14.609740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31e49c08664'
down_revision = '92ce568c9fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'end_date')
    # ### end Alembic commands ###
